import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { FileText, X, Loader2 } from 'lucide-react';
import { useI18n } from '../../i18n/useI18n';
import { API_BASE } from '../../api/client';

interface PolicyBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const PolicyBriefModal: React.FC<PolicyBriefModalProps> = ({ isOpen, onClose }) => {
  const [report, setReport] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { t } = useI18n();

  React.useEffect(() => {
    if (isOpen && !report && !isLoading && !error) {
      generateBrief();
    }
  }, [isOpen]);

  const generateBrief = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetch(`${API_BASE}/api/reports/policy-brief`);
      if (!response.ok) throw new Error('Failed to fetch policy brief');
      const text = await response.text();
      setReport(text);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An unknown error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="surface-card flex h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl shadow-2xl animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b px-6 py-4" style={{ borderColor: 'var(--color-border)' }}>
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-500/10 text-indigo-500">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <h2 className="font-display text-xl font-bold">AI Infrastructure Policy Brief</h2>
              <p className="text-sm" style={{ color: 'var(--color-muted)' }}>Generated by Google Gemini</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-2 transition-colors hover:bg-black/5 dark:hover:bg-white/10"
            aria-label={t.common.cancel}
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 md:p-10">
          {isLoading ? (
            <div className="flex h-full flex-col items-center justify-center space-y-4 text-center">
              <Loader2 className="h-10 w-10 animate-spin text-indigo-500" />
              <p className="font-medium animate-pulse text-lg">Analyzing city infrastructure data...</p>
              <p className="text-sm" style={{ color: 'var(--color-muted)' }}>Gemini is synthesizing real-time civic hotspots.</p>
            </div>
          ) : error ? (
            <div className="flex h-full flex-col items-center justify-center text-center text-red-500">
              <p className="mb-4 text-lg font-bold">Failed to generate report</p>
              <p>{error}</p>
              <button onClick={generateBrief} className="btn-primary mt-6">
                Try Again
              </button>
            </div>
          ) : report ? (
            <div className="prose prose-indigo dark:prose-invert max-w-none">
              <ReactMarkdown>{report}</ReactMarkdown>
            </div>
          ) : null}
        </div>
        
        {/* Footer */}
        <div className="border-t bg-black/5 dark:bg-white/5 px-6 py-4 flex justify-end" style={{ borderColor: 'var(--color-border)' }}>
          <button onClick={onClose} className="btn-secondary">
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
};
